-- Basic data types and utilities.
--
-- Following Section 2 of the paper, a monograded variety is represented by its
-- homogeneous coordinate ring R = k[x]/I, and a bigraded variety by its
-- bihomogeneous coordinate ring k[y,x]/J, where deg(y_j) = (d_j,0) and
-- deg(x_i) = (a_i,c_i).  A bi-to-mono projection -- B2M throughout this
-- package, which predates the paper's current name for it -- is a bigraded
-- variety together with the projection to the monograded variety Proj R
-- (Definition 2.8).
--
-- As an extension beyond the scope of the paper we also allow an affine base:
-- then R is an arbitrary affine ring, X = Spec R, and Z sits in P^(r-1) x X,
-- cut out of k[u,x] by an ideal homogeneous in u alone.  Such a projection is
-- flagged by baseIsProjective => false, and the only difference in the code is
-- that the x variables no longer contribute a cone direction.

B2MProjection = new Type of HashTable
GraphMorphism = new Type of HashTable

-- Whether the base X is Proj R (the situation of the paper) or Spec R.  Hash
-- tables built before this key existed are read as projective.
isProjectiveBase = method()
isProjectiveBase B2MProjection := P ->
    if P#?baseIsProjective then P#baseIsProjective else true

-- Number of cone directions to subtract from a Krull dimension: the fiber cone
-- always, and the cone over the base only when the base is projective.
coneCorrection = method()
coneCorrection B2MProjection := P -> if isProjectiveBase P then 2 else 1

-- Krull dimension of the total space minus the cone directions.
geometricDimension = method()
geometricDimension B2MProjection := P -> dim(P#totalRing) - coneCorrection P

net B2MProjection := P -> (
    "B2M projection Z --> X,  Z subset P^" | toString(#(P#fiberVariables) - 1)
    | " x X,  X = " | (if isProjectiveBase P then "Proj" else "Spec")
    | " R,  dim Z = " | toString geometricDimension P
    )

net GraphMorphism := G -> (
    "graph morphism with graph of dim " | toString(dim(G#totalRing) - 2)
    )

-- The irrelevant ideal of a bigraded polynomial ring k[y,x] is generated by the
-- products y_j x_i (Section 2.3).  Over an affine base only the fiber cone has
-- to be removed, so the irrelevant ideal is generated by the y_j alone.
bigradedIrrelevantIdeal = (ys, xs) -> ideal flatten apply(ys, y -> apply(xs, x -> y*x))
affineIrrelevantIdeal = ys -> ideal ys

-- A bihomogeneous ideal defines a nonempty subvariety of P x X exactly when it
-- does not contain the irrelevant ideal.
definesNonemptyLocus = (q, irr) -> not isSubset(irr, q)

-- Dimension of the subvariety of P x X cut out by a homogeneous ideal.
bigradedDim = (P, q) -> dim((P#ambientRing)/q) - coneCorrection P

-- Map k[y,x] --> R killing the fiber variables; used to restrict bihomogeneous
-- ideals to the base (the ideal p|_R of Section 2.3).
baseProjectionMap = P -> (
    R := P#baseCoordinateRing;
    map(R, P#ambientRing, toList(#(P#fiberVariables) : 0_R) | gens R)
    )

-- Restriction p|_R of a bihomogeneous ideal p, as an ideal of R.
restrictToBase = method()
restrictToBase (B2MProjection, Ideal) := (P, q) -> (
    q0 := eliminate(P#fiberVariables, q);
    trim (baseProjectionMap P) q0
    )

-- Dimension of the image in X of the subvariety defined by q.
imageDimension = (P, q) -> (
    d := dim((P#baseCoordinateRing)/(restrictToBase(P, q)));
    if isProjectiveBase P then d - 1 else d
    )
