doc ///
Key
  FlipComputation
Headline
  computing flips of threefolds
Description
  Text
    This package implements Algorithm 4 (Computing the relative canonical model) of

    T. Yasuda, {\em An algorithm for the minimal model program in dimension
    three}, arXiv:2603.13703,

    together with the auxiliary constructions of Sections 2.4--2.5 of that paper
    (the $w$-diagonal, bi-to-mono projections and graph morphisms).

    A variety $X$ is represented by its homogeneous coordinate ring
    $R = k[x_0,\dots,x_m]/\langle f_1,\dots,f_l\rangle$, where the polynomial
    ring may carry an arbitrary positive grading; that is, $X = \operatorname{Proj} R$ is a
    closed subvariety of a weighted projective space (a {\em monograded
    variety}).  A morphism is represented by its graph inside a product, which is
    a bigraded variety.
  Example
    R = QQ[x0,x1,x2,x3,x4]/ideal(x0*x1-x2*x3);
    P = bigradedReesProjection ideal(x0,x2)
    isNormalSource P
    isSmallProjection P
///

doc ///
Key
  computeFlip
  (computeFlip, Ring)
Headline
  compute the relative canonical model of a birational contraction
Usage
  P = computeFlip R
Inputs
  R:Ring
    the homogeneous coordinate ring of the target $X$ of the contraction
Outputs
  P:B2MProjection
    the relative canonical model $Z \to X$, as a B2M projection, or as a
    @TO GraphMorphism@ if {\tt ReturnGraph => true}
Description
  Text
    This is Algorithm 4 of arXiv:2603.13703.  A canonical divisor
    $K_X = \sum n_i D_i$ is computed, a homogeneous element $s$ with
    $-K_X + \operatorname{div}(s)$ effective is chosen, and the Rees algebras
    $R[I^{(m)}t]$ of the symbolic powers of $I = \mathcal{O}_X(K_X-\operatorname{div}(s))$
    are computed for increasing $m$ until the two conditions of Lemmas 6.6 and
    6.7 hold: $Z^m$ is normal and the exceptional locus of $Z^m \to X$ has
    codimension at least two.  When the contraction is small, this $Z \to X$ is
    its flip, which is the case the examples exhibit.

    Step 3 stops with the identity of $X$ as soon as $I^{(m)}$ has a single
    minimal generator.  At $m = 1$ that is $K_X$ linearly trivial, reported
    before the loop starts; for $m > 1$ it is $K_X$ torsion of order $m$, and
    needs nothing special, the Rees algebra then being $R[u]$ and its projection
    already an isomorphism.  Either way the contraction is a flop, so there is
    no flip, but the relative canonical model exists and is returned.

    With {\tt BaseIsProjective => false} the same algorithm is run over
    $X = \operatorname{Spec} R$; see @TO BaseIsProjective@.

    The two conditions are tested in the order "exceptional locus, then
    normality", and normality is tested as $S_2$ alone: a small projection
    satisfies $R_1$ automatically, see @TO isS2Source@.
Caveat
  The $S_2$ test is exact over an affine base and over a projective base with
  the standard grading; over a weighted grading it is sufficient but not
  necessary, so the loop may try one more $m$ than it strictly has to. See
  @TO isS2Source@.

  Lemma 6.6's test asks the projection to be small, so a relative canonical
  model that is neither the identity nor small -- a divisorial one -- is never
  accepted, and the loop instead runs out of multipliers and raises an error.
  Raising @TO MaxMultiplier@ cannot help in that case.  {\tt MMPComputation}'s
  {\tt relativeCanonicalModelFromBaseData} turns this into an inconclusive
  result rather than an error.
SeeAlso
  BaseIsProjective
  bigradedReesProjection
  isS2Source
  isSmallProjection
  isNormalSource
///

doc ///
Key
  bigradedReesProjection
  (bigradedReesProjection, Ideal)
Headline
  the B2M projection given by the Rees algebra of an ideal
Usage
  P = bigradedReesProjection J
Inputs
  J:Ideal
    a homogeneous ideal of the homogeneous coordinate ring $R$ of $X$
Outputs
  P:B2MProjection
    the projection $\operatorname{Proj} R[Jt] \to \operatorname{Proj} R$
Description
  Text
    The Rees algebra is presented as a bihomogeneous ideal of
    $k[u_1,\dots,u_r,x_0,\dots,x_m]$ with $\deg x_j = (0,c_j)$ and
    $$\deg u_i = (1, d_i - d_0), \qquad d_i = \deg f_i, \quad d_0 = \min_i d_i.$$
    Then $u^a x^b$ has bidegree $(|a|, \deg(f^a x^b) - |a| d_0)$, which is what
    its image $f^a x^b t^{|a|}$ records, so the relations are bihomogeneous
    whatever the degrees of the $f_i$. When the $f_i$ share a degree this is the
    grading $\deg u_i = (1,0)$ of the paper.

    Levelling the generators instead -- replacing $J$ by the ideal generated by
    its top-degree part -- is what this used to do, and it is unsound over a
    weighted base; see @TO singleDegreeIdeal@. {\tt UniformDegree} still forces
    that behaviour, but it is no longer the default.

    With {\tt BaseIsProjective => false} the base is taken to be
    $\operatorname{Spec} R$ instead.  The $x$ variables then carry no grading, the
    relations $u_i - f_i t$ are homogeneous in $u$ whatever the degrees of the
    $f_i$, and no replacement of $J$ is needed.
SeeAlso
  BaseIsProjective
///

doc ///
Key
  BaseIsProjective
Headline
  whether the base of a B2M projection is Proj R or Spec R
Description
  Text
    The paper works throughout with $X = \operatorname{Proj} R$ for a graded ring
    $R$, which is the default.  Passing {\tt BaseIsProjective => false} to
    @TO computeFlip@ or @TO bigradedReesProjection@ makes them work with
    $X = \operatorname{Spec} R$ for an arbitrary affine ring $R$.  The source $Z$
    then still sits in $\mathbf{P}^{r-1} \times X$, cut out by an ideal
    homogeneous in the fiber variables alone, so only the cone over the base
    disappears: the irrelevant ideal becomes $\langle u_1,\dots,u_r\rangle$ and
    one cone direction fewer is subtracted from Krull dimensions.

    An affine base is outside the scope of the paper.  It is provided because it
    makes computations at a single non-Q-Gorenstein singularity far cheaper than
    writing down a projective threefold containing it; see
    {\tt examples/toric-flip.m2}.  @TO b2mToGraphMorphism@ has no affine
    analogue and refuses to run on such a projection.
///

doc ///
Key
  singleDegreeIdeal
  (singleDegreeIdeal, Ideal, ZZ)
Headline
  the ideal generated by the degree-D part
Usage
  J' = singleDegreeIdeal(J, D)
Inputs
  J:Ideal
  D:ZZ
Outputs
  J':Ideal
Caveat
  This used to be how @TO bigradedReesProjection@ forced the generators of
  $I^{(m)}$ into a single degree, on the grounds that the result defines the
  same ideal sheaf once $D$ is at least the largest degree of a generator. That
  holds for the standard grading, where $R_a R_b = R_{a+b}$, but is {\em false}
  for weighted gradings, and it is no longer used by default.

  The ideal generated by $J_D$ is $\sum_i R_{D-d_i} f_i$, and in a weighted ring
  $R_{D-d_i}$ can vanish, dropping $f_i$ outright. Enlarging $D$ does not repair
  this: the $D$ that do preserve the sheaf are sparse and not monotone, and
  sometimes none exists. @TO bigradedReesIdeal@ weights the fibre variables
  instead.
///

doc ///
Key
  canonicalIdeal
  (canonicalIdeal, Ring)
Headline
  the canonical module embedded in R as an ideal of least degree
Usage
  I = canonicalIdeal R
Inputs
  R:Ring
Outputs
  I:Ideal
    an ideal of $R$ isomorphic to $\omega_R$
Description
  Text
    Steps 2 and 3 of Algorithm 4 together amount to embedding $\omega_X$ into
    $R$ as an ideal: the ideal $I = \mathcal{O}_X(K_X - \operatorname{div}(s))$
    of Step 3 is isomorphic to $\omega_X$, and every ideal isomorphic to
    $\omega_X$ arises this way. Rather than choosing $s$ and then forming the
    ideal, this takes a nonzero homomorphism $\omega_X \to R$ of least degree,
    that is a minimal-degree generator of $\operatorname{Hom}(\omega_X, R)$, and
    returns its image.

    It matters which one is used. The $s$ that @TO antiCanonicalSection@
    produces depends on which representative of the canonical class the
    {\tt WeilDivisors} package returns, and that depends on the grading. On the
    threefold of {\tt examples/toric-flip-projective.m2}, graded by
    $(2,2,1)$, that route gives $s = y_3^{11}$ and an $I^{(1)}$ in degree 30,
    which does not finish; the least-degree embedding gives generators of degree
    2 and takes a twentieth of a second.
SeeAlso
  antiCanonicalSection
  flipDivisorData
///

doc ///
Key
  isSmallProjection
  (isSmallProjection, B2MProjection)
Headline
  test whether the exceptional locus has codimension at least two
Usage
  isSmallProjection P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    Reports that $\pi$ is small exactly when no codimension-one component of
    $V(J\mathcal{O}_Z)$ is contracted, $J$ being the blown up ideal.

    That is equivalent to $\operatorname{codim}\operatorname{Exc}(\pi) \ge 2$.
    The exceptional locus is contained in $V(J\mathcal{O}_Z)$, since the blowup
    is an isomorphism wherever $J$ is invertible and $J$ is invertible outside
    $V(J)$. Now $J\mathcal{O}_Z$ is invertible by construction, so
    $V(J\mathcal{O}_Z)$ is an effective Cartier divisor and therefore pure of
    codimension one; a codimension-one component $D$ of the exceptional locus is
    thus a {\em component} of $V(J\mathcal{O}_Z)$ and not merely contained in
    one, because the component containing it has the same dimension. Finally,
    since $X$ is normal and $\pi$ is projective birational, Zariski's main
    theorem makes $\pi$ an isomorphism near any point with finite fibre, so
    components of the exceptional locus are exactly the contracted ones.
Caveat
  By the same argument every relevant component already has codimension one, so
  the dimension test in the implementation cannot fail; it is kept as a safety
  net, and what decides the answer is whether a component is contracted.
///

doc ///
Key
  isS2Source
  (isS2Source, B2MProjection)
Headline
  test Serre's condition S2 on the source
Usage
  isS2Source P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    For a {\em small} projection this is all that has to be checked in order to
    know that $Z$ is normal. A point $z$ of $Z$ of codimension one cannot lie in
    $\operatorname{Exc}(\pi)$, which has codimension at least two, so $\pi$ is a
    local isomorphism at $z$ and $\mathcal{O}_{Z,z}$ is the local ring of $X$ at
    a point of codimension one, hence a discrete valuation ring. A small
    projection therefore satisfies $R_1$ for free.

    The criterion {\tt isNormal} uses for its own $S_2$ half is that
    $\operatorname{codim}\operatorname{Ext}^j(A,S) \ge j+2$ for every
    $j > \operatorname{codim} I$; the locus where it fails is the union over $j$
    of the components of $\operatorname{Supp}\operatorname{Ext}^j$ of
    codimension at most $j+1$. Since $Z$ is covered by the primes of $A$ that do
    not contain the irrelevant ideal, $Z$ satisfies $S_2$ exactly when every
    such bad component lies in the irrelevant locus. That is the same step as in
    @TO isSmallProjection@, and it needs neither an affine cover nor a Veronese
    computation.

    Applying the criterion to the whole of $\operatorname{Spec} A$ instead --
    that is, asking the cone to be $S_2$ -- is strictly more than Lemma 6.6 asks
    for, because the vertex locus
    $V(A_+) \cong \operatorname{Spec} R$ has codimension one in
    $\operatorname{Spec} A$.
    The test is sufficient whatever the weights: writing $B = A_f$ for a
    relevant homogeneous $f$, $B$ is finite over $B' = B_0[f,f^{-1}]$ and $B'$
    is a direct summand of $B$ as a $B'$-module, so $B$ being $S_2$ forces
    $B_0 = A_{(f)}$ to be $S_2$. It is moreover {\em necessary}, hence exactly
    the condition of Lemma 6.6, when every relevant variable has weight one: the
    torus then acts freely on $\operatorname{Spec} A \setminus V(\mathrm{irr})$,
    which becomes a torsor over $Z$ and lets $S_2$ travel in both directions.
    That covers an affine base and a projective base with the standard grading.
Caveat
  On its own this does not say that $Z$ is normal: it has to be combined with
  @TO isSmallProjection@.

  Over a weighted grading only sufficiency is claimed. That costs nothing in
  correctness: a sufficiently factorial $m$ makes
  $A = \bigoplus_k \mathcal{O}_X(-kmE)$, a divisorial algebra over a normal ring
  and hence normal, so the test is certain to fire by then. At worst
  @TO computeFlip@ tries one more $m$ than strictly necessary.
SeeAlso
  isNormalSource
  isSmallProjection
///

doc ///
Key
  b2mDiagonalData
  (b2mDiagonalData, B2MProjection)
Headline
  choose a positive diagonal for a projective B2M projection
Usage
  data = b2mDiagonalData P
Inputs
  P:B2MProjection
Outputs
  data:HashTable
Description
  Text
    For fibre degrees $(p_j,e_j)$, choose an integral slope
    $D>\max_j(e_j/p_j)$ and return the Hilbert basis for the transformed
    positive weights $Dp_j-e_j$, together with the monograded coordinate ring
    and its degrees.  When every $e_j$ is zero this is the usual Segre diagonal.
SeeAlso
  b2mToGraphMorphism
  segreHilbertBasis
///

doc ///
Key
  b2mToGraphMorphism
  (b2mToGraphMorphism, B2MProjection)
Headline
  transform a B2M projection into a graph morphism
Usage
  G = b2mToGraphMorphism P
Inputs
  P:B2MProjection
Outputs
  G:GraphMorphism
Description
  Text
    This is Lemma 2.10 of arXiv:2603.13703.  The source of the projection is
    turned into a monograded variety by means of the Segre isomorphism of
    Section 2.4, and the graph of the resulting morphism is computed as a
    bigraded variety.  For a skew fibre block with degrees $(p_j,e_j)$, the
    implementation chooses an integral slope $D>e_j/p_j$ and applies the same
    affine-semigroup construction to the positive weights $Dp_j-e_j$.
SeeAlso
  b2mDiagonalData
///

doc ///
Key
  B2MProjection
Headline
  a bigraded variety together with its projection to a monograded variety
Description
  Text
    Definition 2.8 of arXiv:2603.13703, where it is called a bi-to-mono
    projection; B2M is this package's own older name for it.  The source $Z$
    is a bigraded variety
    sitting in $\mathbf{P}^{r-1} \times X$, the base $X$ is the monograded
    variety $\operatorname{Proj} R$, and the projection $\pi : Z \to X$ is the
    restriction of the second projection.  This is the form in which
    @TO computeFlip@ returns its relative canonical model.

    As an extension beyond the scope of the paper the base may instead be
    $\operatorname{Spec} R$; see @TO BaseIsProjective@ and @TO isProjectiveBase@.

    A projection is a hash table with the following keys.

      @TO ambientRing@ -- the bigraded polynomial ring $k[u,x]$

      @TO definingIdeal@ -- the bihomogeneous ideal of $Z$ in it

      @TO totalRing@ -- the quotient by that ideal

      @TO baseCoordinateRing@ -- the ring $R$ of the base

      @TO fiberVariables@, @TO baseVariables@ -- the $u_i$ and the $x_j$

      @TO irrelevantIdeal@ -- the ideal whose vanishing locus is empty

      @TO blownUpIdeal@ -- the ideal of $R$ that was blown up, in $k[u,x]$

      @TO uniformDegreeUsed@ -- the {\tt UniformDegree} passed, or {\tt null}
  Example
    R = QQ[x0,x1,x2,x3,x4]/ideal(x0*x1-x2*x3);
    P = bigradedReesProjection ideal(x0,x2)
    geometricDimension P
SeeAlso
  GraphMorphism
  bigradedReesProjection
  computeFlip
///

doc ///
Key
  GraphMorphism
Headline
  a morphism of monograded varieties, presented by its graph
Description
  Text
    Section 2.5 of arXiv:2603.13703.  A morphism $W \to X$ of monograded
    varieties is recorded as its graph inside $W \times X$, which is a bigraded
    variety.  @TO b2mToGraphMorphism@ produces one from a @TO B2MProjection@,
    and @TO computeFlip@ returns one when {\tt ReturnGraph => true}.

    The keys are @TO ambientRing@, @TO definingIdeal@, @TO totalRing@,
    @TO sourceRing@, @TO baseCoordinateRing@, @TO fiberVariables@,
    @TO baseVariables@ and @TO irrelevantIdeal@, with the same meanings as for a
    @TO B2MProjection@ except that @TO sourceRing@ now carries the monograded
    model $W$ of the source and the fiber variables are the Segre coordinates.
SeeAlso
  B2MProjection
  b2mToGraphMorphism
///

doc ///
Key
  ambientRing
Headline
  the bigraded polynomial ring a B2M projection lives in
Description
  Text
    The ring $k[u_1,\dots,u_r,x_0,\dots,x_n]$, bigraded so that the relations of
    the Rees algebra are bihomogeneous.  Its quotient by @TO definingIdeal@ is
    @TO totalRing@.
SeeAlso
  B2MProjection
///

doc ///
Key
  definingIdeal
Headline
  the bihomogeneous ideal cutting out the source
Description
  Text
    The ideal of @TO ambientRing@ defining $Z$, homogeneous for both gradings.
SeeAlso
  B2MProjection
///

doc ///
Key
  totalRing
Headline
  the bihomogeneous coordinate ring of the source
Description
  Text
    The quotient of @TO ambientRing@ by @TO definingIdeal@, that is the affine
    cone over $Z$.  Note that its Krull dimension exceeds $\dim Z$ by the number
    of cone directions; @TO geometricDimension@ makes the correction.
SeeAlso
  B2MProjection
  geometricDimension
///

doc ///
Key
  sourceRing
Headline
  the monograded coordinate ring of the source of a graph morphism
Description
  Text
    The ring $W$ obtained from the source of a @TO B2MProjection@ by the Segre
    isomorphism of Proposition 2.6.  Present only on a @TO GraphMorphism@.
SeeAlso
  GraphMorphism
  b2mToGraphMorphism
///

doc ///
Key
  baseCoordinateRing
Headline
  the homogeneous coordinate ring of the base
Description
  Text
    The ring $R$, so that the base is $\operatorname{Proj} R$ or, when
    @TO isProjectiveBase@ is false, $\operatorname{Spec} R$.
Caveat
  Not to be confused with {\tt baseRing}, which belongs to Macaulay2 itself.
  This key was called {\tt baseRing} before version 0.2.0 and was renamed
  because it hid that function.
SeeAlso
  B2MProjection
///

doc ///
Key
  fiberVariables
Headline
  the variables of the fiber direction
Description
  Text
    The $u_1,\dots,u_r$, one for each generator of the ideal being blown up.
SeeAlso
  B2MProjection
  baseVariables
///

doc ///
Key
  baseVariables
Headline
  the variables coming from the base
Description
  Text
    The images in @TO ambientRing@ of the variables of the ambient ring of
    @TO baseCoordinateRing@.
SeeAlso
  B2MProjection
  fiberVariables
///

doc ///
Key
  irrelevantIdeal
Headline
  the ideal whose vanishing locus is empty
Description
  Text
    Over a projective base this is generated by the products $u_i x_j$
    (Section 2.1); over an affine base only the fiber cone has to be removed, so
    it is generated by the $u_i$ alone.  A bihomogeneous ideal defines a nonempty
    subvariety exactly when it does not contain this one, which is how
    @TO isSmallProjection@ and @TO isS2Source@ discard components that are not
    really there.
SeeAlso
  B2MProjection
///

doc ///
Key
  blownUpIdeal
Headline
  the ideal that was blown up, as an ideal of the ambient bigraded ring
Description
  Text
    The image of $J$ in @TO ambientRing@, where the projection is
    $\operatorname{Proj} R[Jt] \to \operatorname{Proj} R$.  Its generators are
    what @TO isSmallProjection@ tests, and in the toric examples reading them off
    recovers the fan of $Z$.
SeeAlso
  B2MProjection
  bigradedReesProjection
///

doc ///
Key
  uniformDegreeUsed
Headline
  the UniformDegree that was applied, or null
Description
  Text
    Records the {\tt UniformDegree} passed to @TO bigradedReesProjection@.  It is
    {\tt null} in the default, correct mode, in which the generators are left
    alone and the fiber variables are weighted instead.
SeeAlso
  UniformDegree
  singleDegreeIdeal
///

doc ///
Key
  geometricDimension
  (geometricDimension, B2MProjection)
Headline
  the dimension of the source, with the cone directions removed
Usage
  d = geometricDimension P
Inputs
  P:B2MProjection
Outputs
  d:ZZ
Description
  Text
    The Krull dimension of @TO totalRing@ minus the number of cone directions:
    two over a projective base, where both the fiber and the base contribute a
    cone, and one over an affine base.
  Example
    R = QQ[x0,x1,x2,x3,x4]/ideal(x0*x1-x2*x3);
    geometricDimension bigradedReesProjection ideal(x0,x2)
SeeAlso
  B2MProjection
///

doc ///
Key
  isProjectiveBase
  (isProjectiveBase, B2MProjection)
Headline
  whether the base is Proj R rather than Spec R
Usage
  isProjectiveBase P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    Reports how the projection was built.  Projections made before this
    distinction existed are read as projective.
SeeAlso
  BaseIsProjective
///

doc ///
Key
  restrictToBase
  (restrictToBase, B2MProjection, Ideal)
Headline
  the restriction of a bihomogeneous ideal to the base
Usage
  q0 = restrictToBase(P, q)
Inputs
  P:B2MProjection
  q:Ideal
    a bihomogeneous ideal of @TO ambientRing@
Outputs
  q0:Ideal
    an ideal of @TO baseCoordinateRing@
Description
  Text
    The ideal $\mathfrak{p}|_R$ of Section 2.3, obtained by eliminating the fiber
    variables and then mapping them to zero.  It defines the image in $X$ of the
    subvariety cut out by $q$, which is what @TO isSmallProjection@ compares
    dimensions against.
SeeAlso
  B2MProjection
  isSmallProjection
///

doc ///
Key
  canonicalDivisorData
  (canonicalDivisorData, Ring)
Headline
  a canonical divisor of X, as prime-multiplicity pairs
Usage
  Kdata = canonicalDivisorData R
Inputs
  R:Ring
Outputs
  Kdata:List
    pairs $\{p_i, n_i\}$ with $p_i$ a height-one prime and $n_i \ne 0$, so that
    $K_X = \sum n_i D_i$ with $D_i = V(p_i)$
Description
  Text
    Step 1 of Algorithm 4.  The canonical module is computed by the {\tt WeilDivisors}
    package as $\operatorname{Ext}^t(R,\omega)$.
  Example
    R = QQ[x0,x1,x2,x3];
    canonicalDivisorData R
  Text
    which reads $K_{\mathbf{P}^3} = -4H$.
Caveat
  Which representative of the canonical class comes back depends on the grading,
  and over a weighted grading it can be a bad one; that is the reason
  @TO flipDivisorData@ prefers @TO canonicalIdeal@ to the route through
  @TO antiCanonicalSection@.
SeeAlso
  antiCanonicalSection
  flipDivisorData
///

doc ///
Key
  antiCanonicalSection
  (antiCanonicalSection, Ring)
  (antiCanonicalSection, Ring, List)
Headline
  a homogeneous s of least degree with -K_X + div(s) effective
Usage
  s = antiCanonicalSection R
  s = antiCanonicalSection(R, Kdata)
Inputs
  R:Ring
  Kdata:List
    the output of @TO canonicalDivisorData@, computed afresh if omitted
Outputs
  s:RingElement
Description
  Text
    Step 2 of Algorithm 4: an element of $\prod_i p_i^{\max(0,n_i)}$, taken of
    least degree among the generators of that product.  When every $n_i$ is
    negative -- which happens routinely in the toric examples -- the product is
    the unit ideal and $s = 1$.
Caveat
  This is the paper's construction and it is kept for that reason, but it is not
  what @TO flipDivisorData@ does by default.  The $s$ produced here inherits
  whatever representative of $K_X$ the {\tt WeilDivisors} package returns; over a
  weighted grading that can force $I^{(m)}$ into an enormous degree, and the
  computation becomes hopeless.  See @TO canonicalIdeal@.
SeeAlso
  canonicalIdeal
  canonicalDivisorData
///

doc ///
Key
  flipDivisorData
  (flipDivisorData, Ring)
Headline
  the divisor E with I = O_X(-E) isomorphic to omega_X
Usage
  (s, Edata) = flipDivisorData R
Inputs
  R:Ring
Outputs
  :Sequence
    the section used, or {\tt null} when the embedding route was taken, followed
    by pairs $\{p_i, e_i\}$ describing $E$
Description
  Text
    Step 3 of Algorithm 4.  By default $I$ is @TO canonicalIdeal@, an embedding
    $\omega_X \hookrightarrow R$ of least degree, and $E$ is the divisor of that
    ideal; passing {\tt AntiCanonicalSection => s} follows the paper instead and
    forms $\operatorname{div}(s) - K_X$.

    $E$ is effective because $I$ is an ideal of $R$, and $-E$ is linearly
    equivalent to $K_X$ because $I$ is isomorphic to $\omega_X$.
    An empty list of pairs means $E = 0$, that is, $K_X$ is linearly trivial.
    Every $I^{(m)}$ is then the unit ideal, so Step 3 finds $r = 1$ at $m = 1$
    and the relative canonical model is the identity of $X$; @TO computeFlip@
    returns it.  The contraction is a flop in that case, so there is no flip,
    but the relative canonical model exists all the same.
Caveat
  An error is raised when $E$ turns out not to be effective, which can only
  happen on the {\tt AntiCanonicalSection} route.
SeeAlso
  canonicalIdeal
  divisorialIdeal
  computeFlip
///

doc ///
Key
  divisorialIdeal
  (divisorialIdeal, List, ZZ)
Headline
  the divisorial ideal O_X(-mE)
Usage
  Im = divisorialIdeal(Edata, m)
Inputs
  Edata:List
    the second component of the output of @TO flipDivisorData@
  m:ZZ
Outputs
  Im:Ideal
Description
  Text
    The symbolic power $I^{(m)}$ of Step 5.  Mathematically this is
    $\bigcap_i p_i^{(m e_i)}$, but computing it that way through
    {\tt SymbolicPowers} is ruinous, because the saturations blow up with $m$:
    3.2 seconds at $m = 8$ on the threefold of {\tt examples/toric-flip.m2}, and
    far worse beyond.  The {\tt WeilDivisors} package builds $\mathcal{O}_X(-D)$ from
    products of ordinary powers and a reflexive hull instead, which on the same
    example takes about 0.006 seconds and is essentially flat in $m$.  The two
    agree.
SeeAlso
  flipDivisorData
///

doc ///
Key
  bigradedReesIdeal
  (bigradedReesIdeal, Ideal)
Headline
  the Rees algebra of an ideal, as a bihomogeneous ideal
Usage
  (A, IZ) = bigradedReesIdeal J
Inputs
  J:Ideal
Outputs
  :Sequence
    the bigraded polynomial ring $k[u,x]$, and the ideal of $R[Jt]$ in it
Description
  Text
    The kernel of $k[u,x] \to R[t]$, $u_i \mapsto f_i t$, computed by giving $t$
    the degree $(1,-d_0)$ and eliminating it.  The grading is the one described
    at @TO bigradedReesProjection@; over an affine base the $u$-degree alone is
    used and is left implicit, since none of the operations involved needs it.
SeeAlso
  bigradedReesProjection
///

doc ///
Key
  isNormalSource
  (isNormalSource, B2MProjection)
Headline
  test normality of the affine cone over the source
Usage
  isNormalSource P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    Asks {\tt isNormal} of @TO totalRing@.  This is sufficient for $Z$ to be
    normal but not necessary, and it is expensive: {\tt isNormal} checks $S_2$
    and then $R_1$, and the $R_1$ half goes through
    {\tt minors(codim I, jacobian)}, which explodes.  On one nine-variable
    example the $S_2$ half took 0.02 seconds and the $R_1$ half 119, with the
    minors having 1,436,495 generators.
Caveat
  @TO computeFlip@ does not use this.  Once the projection is known to be small,
  $R_1$ is automatic and normality reduces to @TO isS2Source@, which is the test
  actually run.
SeeAlso
  isS2Source
  isSmallProjection
///

doc ///
Key
  segreHilbertBasis
  (segreHilbertBasis, List, List)
Headline
  the Hilbert basis of the monoid defining a Segre product
Usage
  HB = segreHilbertBasis(ds, cs)
Inputs
  ds:List
    the weights $d_j$ of the first factor
  cs:List
    the weights $c_i$ of the second
Outputs
  HB:List
    the Hilbert basis, as exponent vectors
Description
  Text
    Lemma 2.7 of arXiv:2603.13703.  The monoid is
    $$A = \{(b,a) \in \mathbf{N}^{n+1}\times\mathbf{N}^{m+1} :
      \textstyle\sum_j d_j b_j = \sum_i c_i a_i\},$$
    and its Hilbert basis gives the monomial generators of the Segre product
    $k[y] \# k[x]$.
  Example
    #segreHilbertBasis({1,1},{1,1})
    #segreHilbertBasis({1,1},{1,2})
  Text
    The first is the Segre product of two copies of $\mathbf{P}^1$, with the four
    generators one expects; the weighted case needs a fifth.
SeeAlso
  segreProductRing
  b2mToGraphMorphism
///

doc ///
Key
  segreProductRing
  (segreProductRing, Ring, List, List)
Headline
  a polynomial ring mapping onto a Segre product
Usage
  (T, HB, zdegs) = segreProductRing(kk, ds, cs)
Inputs
  kk:Ring
    the coefficient field
  ds:List
  cs:List
Outputs
  :Sequence
    a polynomial ring $k[z_1,\dots,z_s]$, the exponent vectors of the
    corresponding monomials, and their degrees
Description
  Text
    One variable for each element of @TO segreHilbertBasis@, graded by the degree
    of the monomial it stands for.  @TO b2mToGraphMorphism@ maps it onto the
    Segre product and takes the kernel.
SeeAlso
  segreHilbertBasis
///

doc ///
Key
  graphMorphismIdeal
  (graphMorphismIdeal, GraphMorphism)
Headline
  the bihomogeneous ideal defining a graph
Usage
  I = graphMorphismIdeal G
Inputs
  G:GraphMorphism
Outputs
  I:Ideal
Description
  Text
    The same thing as {\tt G#definingIdeal}.
Caveat
  Called {\tt graphIdeal} before version 0.2.0, which hid Macaulay2's own
  {\tt graphIdeal} for ring maps.
SeeAlso
  GraphMorphism
  definingIdeal
///

doc ///
Key
  uniformDegree
  (uniformDegree, Ideal)
Headline
  the largest degree of a generator
Usage
  D = uniformDegree J
Inputs
  J:Ideal
Outputs
  D:ZZ
Description
  Text
    The degree the paper's Step 5 implicitly levels the generators to, and the
    natural argument to {\tt UniformDegree}.  It is useful mainly for seeing
    whether the generators share a degree in the first place: they do exactly
    when {\tt degrees J} is constant, and only then does the paper's grading
    $\deg u_i = (1,0)$ apply.
SeeAlso
  UniformDegree
  singleDegreeIdeal
///

doc ///
Key
  AntiCanonicalSection
Headline
  follow the paper's Step 2 with a given section
Description
  Text
    Passing {\tt AntiCanonicalSection => s} makes @TO flipDivisorData@ and
    @TO computeFlip@ form $E = \operatorname{div}(s) - K_X$, which is Step 3 of
    the paper.  The default, {\tt null}, embeds $\omega_X$ into $R$ directly with
    @TO canonicalIdeal@ and is very much faster over a weighted grading.
Caveat
  Called {\tt Section} before version 0.2.0.  That name collided with
  {\tt SimpleDoc}'s and made the package impossible to install.
SeeAlso
  antiCanonicalSection
  canonicalIdeal
///

doc ///
Key
  Multipliers
Headline
  the multipliers m to try, in order
Description
  Text
    A list, replacing the default $1, 2, 3, \dots$ of @TO MaxMultiplier@.  Since
    any $m$ that works gives the same answer, this is chiefly a way to pin an
    example to the $m$ known to settle it, or to check that a smaller $m$ really
    is rejected.
SeeAlso
  MaxMultiplier
///

doc ///
Key
  MaxMultiplier
Headline
  the largest multiplier m the search will try
Description
  Text
    @TO computeFlip@ tries $m = 1, 2, 3, \dots$ up to {\tt MaxMultiplier}, which
    is the order Algorithm 4 of the paper prescribes.  The default is 24.

    Consecutive $m$ is what finds the smallest working one, and that is what
    matters: the cost of an iteration grows very steeply in $m$, because the
    number of generators of $I^{(m)}$ -- and with it the number of variables of
    the Rees algebra -- grows with $m$.  On the threefold of
    {\tt examples/toric-flip.m2} one iteration costs 0.02 s at $m=1$, 0.9 s at
    $m=6$, 7 s at $m=8$, and more than ten minutes at $m=12$.

    Earlier releases instead tried every divisor of {\tt MaxSteps}$!$, because
    v2 of the paper guaranteed termination only along $m = 1!, 2!, 3!, \dots$
    and the divisors of $n!$ are the small values that keep those factorials in
    the list.  Lemma 6.6 carries no divisibility condition on $m$, so that
    detour is gone; it had been skipping values ($5, 7, 9, \dots$) at which a
    cheap answer could have been found, only to pay for a much larger $m$
    afterwards.
SeeAlso
  Multipliers
///

doc ///
Key
  ReturnGraph
Headline
  return the flip as a graph morphism
Description
  Text
    With {\tt ReturnGraph => true}, @TO computeFlip@ passes its answer through
    @TO b2mToGraphMorphism@ and returns a @TO GraphMorphism@ instead of a
    @TO B2MProjection@.  This needs a projective base and fiber variables without
    weights.
SeeAlso
  b2mToGraphMorphism
///

doc ///
Key
  UniformDegree
Headline
  level the generators to a single degree before blowing up
Description
  Text
    Replaces $J$ by the ideal generated by its degree-$D$ part, which is how the
    paper's Step 5 arranges for the Rees relations to be bihomogeneous.
Caveat
  Sound only for the standard grading.  Over a weighted grading it can drop a
  generator and blow up a different ideal; see @TO singleDegreeIdeal@.  It is not
  the default, and the default needs no levelling at all.
SeeAlso
  singleDegreeIdeal
  uniformDegree
  uniformDegreeUsed
///

doc ///
Key
  [computeFlip, AntiCanonicalSection]
Headline
  follow the paper's Step 2 with a given section
Usage
  computeFlip(R, AntiCanonicalSection => s)
Description
  Text
    See @TO AntiCanonicalSection@.
///

doc ///
Key
  [computeFlip, Multipliers]
Headline
  the multipliers m to try, in order
Usage
  computeFlip(R, Multipliers => ms)
Description
  Text
    See @TO Multipliers@.
///

doc ///
Key
  [computeFlip, MaxMultiplier]
Headline
  the largest multiplier m the search will try
Usage
  computeFlip(R, MaxMultiplier => n)
Description
  Text
    See @TO MaxMultiplier@.
///

doc ///
Key
  [computeFlip, ReturnGraph]
Headline
  return the flip as a graph morphism
Usage
  computeFlip(R, ReturnGraph => true)
Description
  Text
    See @TO ReturnGraph@.
///

doc ///
Key
  [computeFlip, BaseIsProjective]
Headline
  run the algorithm over an affine base
Usage
  computeFlip(R, BaseIsProjective => false)
Description
  Text
    See @TO BaseIsProjective@.
///

doc ///
Key
  [computeFlip, Verbose]
Headline
  report each multiplier and each test as it is tried
Usage
  computeFlip(R, Verbose => false)
Description
  Text
    On by default here, since a run can take a long time and the progress
    through the multipliers is the useful thing to watch.
///

doc ///
Key
  [bigradedReesProjection, UniformDegree]
Headline
  level the generators to a single degree before blowing up
Usage
  bigradedReesProjection(J, UniformDegree => D)
Description
  Text
    See @TO UniformDegree@.
///

doc ///
Key
  [bigradedReesProjection, BaseIsProjective]
Headline
  build the projection over an affine base
Usage
  bigradedReesProjection(J, BaseIsProjective => false)
Description
  Text
    See @TO BaseIsProjective@.
///

doc ///
Key
  [bigradedReesIdeal, BaseIsProjective]
Headline
  present the Rees algebra over an affine base
Usage
  bigradedReesIdeal(J, BaseIsProjective => false)
Description
  Text
    See @TO BaseIsProjective@.
///

doc ///
Key
  [canonicalDivisorData, BaseIsProjective]
Headline
  compute the canonical divisor of an affine ring
Usage
  canonicalDivisorData(R, BaseIsProjective => false)
Description
  Text
    Passed to the {\tt WeilDivisors} package as its {\tt IsGraded} option.  See
    @TO BaseIsProjective@.
///

doc ///
Key
  [antiCanonicalSection, BaseIsProjective]
Headline
  choose a section over an affine base
Usage
  antiCanonicalSection(R, BaseIsProjective => false)
Description
  Text
    See @TO BaseIsProjective@.
///

doc ///
Key
  [flipDivisorData, AntiCanonicalSection]
Headline
  follow the paper's Step 3 with a given section
Usage
  flipDivisorData(R, AntiCanonicalSection => s)
Description
  Text
    See @TO AntiCanonicalSection@.
///

doc ///
Key
  [flipDivisorData, BaseIsProjective]
Headline
  compute E over an affine base
Usage
  flipDivisorData(R, BaseIsProjective => false)
Description
  Text
    See @TO BaseIsProjective@.
///

doc ///
Key
  [isSmallProjection, Verbose]
Headline
  report the dimension of each component and whether it is contracted
Usage
  isSmallProjection(P, Verbose => true)
Description
  Text
    Off by default.  @TO computeFlip@ turns it on when it is itself verbose.
///

doc ///
Key
  [b2mToGraphMorphism, Verbose]
Headline
  report the size of the Segre product
Usage
  b2mToGraphMorphism(P, Verbose => true)
Description
  Text
    Off by default.
///
