doc ///
Key
  FlipComputation
Headline
  computing flips of threefolds
Description
  Text
    This package implements Algorithm 3 (Computing a flip) of

    T. Yasuda, {\em An algorithm for the minimal model program in dimension
    three}, arXiv:2603.13703,

    together with the auxiliary constructions of Sections 2.2--2.4 of that paper
    (Segre products, B2M projections and graph morphisms).

    A variety $X$ is represented by its homogeneous coordinate ring
    $R = k[x_0,\dots,x_m]/\langle f_1,\dots,f_l\rangle$, where the polynomial
    ring may carry an arbitrary positive grading; that is, $X = \operatorname{Proj} R$ is a
    closed subvariety of a weighted projective space (a {\em monograded
    variety}).  A morphism is represented by its graph inside a product, which is
    a bigraded variety.
  Example
    R = QQ[x0,x1,x2,x3,x4]/ideal(x0*x1-x2*x3);
    P = bigradedReesProjection ideal(x0,x2)
    isNormalSource P
    isSmallProjection P
///

doc ///
Key
  computeFlip
  (computeFlip, Ring)
Headline
  compute the flip of a flipping contraction
Usage
  P = computeFlip R
Inputs
  R:Ring
    the homogeneous coordinate ring of the target $X$ of a flipping contraction
Outputs
  P:B2MProjection
    the flip $Z \to X$, as a B2M projection, or as a @TO GraphMorphism@ if
    {\tt ReturnGraph => true}
Description
  Text
    This is Algorithm 3 of arXiv:2603.13703.  A canonical divisor
    $K_X = \sum n_i D_i$ is computed, a homogeneous element $s$ with
    $-K_X + \operatorname{div}(s)$ effective is chosen, and the Rees algebras
    $R[I^{(m)}t]$ of the symbolic powers of $I = \mathcal{O}_X(K_X-\operatorname{div}(s))$
    are computed for $m = 1!, 2!, 3!, \dots$ until the two conditions of Lemma
    7.2 hold: $Z^m$ is normal and the exceptional locus of $Z^m \to X$ has
    codimension at least two.

    With {\tt BaseIsProjective => false} the same algorithm is run over
    $X = \operatorname{Spec} R$; see @TO BaseIsProjective@.
Caveat
  The normality test is applied to the bihomogeneous coordinate ring, that is, to
  the affine cone over $Z^m$; this is sufficient but not necessary for $Z^m$
  itself to be normal.
SeeAlso
  BaseIsProjective
  bigradedReesProjection
  isSmallProjection
  isNormalSource
///

doc ///
Key
  bigradedReesProjection
  (bigradedReesProjection, Ideal)
Headline
  the B2M projection given by the Rees algebra of an ideal
Usage
  P = bigradedReesProjection J
Inputs
  J:Ideal
    a homogeneous ideal of the homogeneous coordinate ring $R$ of $X$
Outputs
  P:B2MProjection
    the projection $\operatorname{Proj} R[Jt] \to \operatorname{Proj} R$
Description
  Text
    The Rees algebra is presented as a bihomogeneous ideal of
    $k[u_1,\dots,u_r,x_0,\dots,x_m]$ with $\deg u_i = (1,0)$ and
    $\deg x_j = (0,c_j)$.  For the relations to be bihomogeneous, the generators
    of the ideal must all have the same degree, so $J$ is replaced by the ideal
    generated by its degree-$D$ part, where $D$ is the largest degree of a
    generator; this does not change the associated ideal sheaf and hence not the
    blowup.

    With {\tt BaseIsProjective => false} the base is taken to be
    $\operatorname{Spec} R$ instead.  The $x$ variables then carry no grading, the
    relations $u_i - f_i t$ are homogeneous in $u$ whatever the degrees of the
    $f_i$, and no replacement of $J$ is needed.
SeeAlso
  BaseIsProjective
///

doc ///
Key
  BaseIsProjective
Headline
  whether the base of a B2M projection is Proj R or Spec R
Description
  Text
    The paper works throughout with $X = \operatorname{Proj} R$ for a graded ring
    $R$, which is the default.  Passing {\tt BaseIsProjective => false} to
    @TO computeFlip@ or @TO bigradedReesProjection@ makes them work with
    $X = \operatorname{Spec} R$ for an arbitrary affine ring $R$.  The source $Z$
    then still sits in $\mathbf{P}^{r-1} \times X$, cut out by an ideal
    homogeneous in the fiber variables alone, so only the cone over the base
    disappears: the irrelevant ideal becomes $\langle u_1,\dots,u_r\rangle$ and
    one cone direction fewer is subtracted from Krull dimensions.

    An affine base is outside the scope of the paper.  It is provided because it
    makes computations at a single non-Q-Gorenstein singularity far cheaper than
    writing down a projective threefold containing it; see
    {\tt examples/toric-flip.m2}.  @TO b2mToGraphMorphism@ has no affine
    analogue and refuses to run on such a projection.
///

doc ///
Key
  isSmallProjection
  (isSmallProjection, B2MProjection)
Headline
  test whether the exceptional locus has codimension at least two
Usage
  isSmallProjection P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    The exceptional locus of the blowup of an ideal $J$ is contained in
    $V(J\mathcal{O}_Z)$, since the blowup is an isomorphism where $J$ is
    invertible.  As $X$ is normal and the projection is projective and
    birational, Zariski's main theorem shows that any divisorial component of the
    exceptional locus is an irreducible component of $V(J\mathcal{O}_Z)$ of
    codimension one that is contracted.  The test looks for such components.
///

doc ///
Key
  b2mToGraphMorphism
  (b2mToGraphMorphism, B2MProjection)
Headline
  transform a B2M projection into a graph morphism
Usage
  G = b2mToGraphMorphism P
Inputs
  P:B2MProjection
Outputs
  G:GraphMorphism
Description
  Text
    This is Lemma 2.6 of arXiv:2603.13703.  The source of the projection is
    turned into a monograded variety by means of the Segre isomorphism of
    Section 2.2, and the graph of the resulting morphism is computed as a
    bigraded variety.
///
