doc ///
Key
  FlipComputation
Headline
  computing flips of threefolds
Description
  Text
    This package implements Algorithm 3 (Computing a flip) of

    T. Yasuda, {\em An algorithm for the minimal model program in dimension
    three}, arXiv:2603.13703,

    together with the auxiliary constructions of Sections 2.2--2.4 of that paper
    (Segre products, B2M projections and graph morphisms).

    A variety $X$ is represented by its homogeneous coordinate ring
    $R = k[x_0,\dots,x_m]/\langle f_1,\dots,f_l\rangle$, where the polynomial
    ring may carry an arbitrary positive grading; that is, $X = \operatorname{Proj} R$ is a
    closed subvariety of a weighted projective space (a {\em monograded
    variety}).  A morphism is represented by its graph inside a product, which is
    a bigraded variety.
  Example
    R = QQ[x0,x1,x2,x3,x4]/ideal(x0*x1-x2*x3);
    P = bigradedReesProjection ideal(x0,x2)
    isNormalSource P
    isSmallProjection P
///

doc ///
Key
  computeFlip
  (computeFlip, Ring)
Headline
  compute the flip of a flipping contraction
Usage
  P = computeFlip R
Inputs
  R:Ring
    the homogeneous coordinate ring of the target $X$ of a flipping contraction
Outputs
  P:B2MProjection
    the flip $Z \to X$, as a B2M projection, or as a @TO GraphMorphism@ if
    {\tt ReturnGraph => true}
Description
  Text
    This is Algorithm 3 of arXiv:2603.13703.  A canonical divisor
    $K_X = \sum n_i D_i$ is computed, a homogeneous element $s$ with
    $-K_X + \operatorname{div}(s)$ effective is chosen, and the Rees algebras
    $R[I^{(m)}t]$ of the symbolic powers of $I = \mathcal{O}_X(K_X-\operatorname{div}(s))$
    are computed for $m = 1!, 2!, 3!, \dots$ until the two conditions of Lemma
    7.2 hold: $Z^m$ is normal and the exceptional locus of $Z^m \to X$ has
    codimension at least two.

    With {\tt BaseIsProjective => false} the same algorithm is run over
    $X = \operatorname{Spec} R$; see @TO BaseIsProjective@.

    The two conditions are tested in the order "exceptional locus, then
    normality", and normality is tested as $S_2$ alone: a small projection
    satisfies $R_1$ automatically, see @TO isS2Source@.
Caveat
  The $S_2$ test is applied to the bihomogeneous coordinate ring, that is, to
  the affine cone over $Z^m$; this is sufficient but not necessary for $Z^m$
  itself to be $S_2$.
SeeAlso
  BaseIsProjective
  bigradedReesProjection
  isS2Source
  isSmallProjection
  isNormalSource
///

doc ///
Key
  bigradedReesProjection
  (bigradedReesProjection, Ideal)
Headline
  the B2M projection given by the Rees algebra of an ideal
Usage
  P = bigradedReesProjection J
Inputs
  J:Ideal
    a homogeneous ideal of the homogeneous coordinate ring $R$ of $X$
Outputs
  P:B2MProjection
    the projection $\operatorname{Proj} R[Jt] \to \operatorname{Proj} R$
Description
  Text
    The Rees algebra is presented as a bihomogeneous ideal of
    $k[u_1,\dots,u_r,x_0,\dots,x_m]$ with $\deg x_j = (0,c_j)$ and
    $$\deg u_i = (1, d_i - d_0), \qquad d_i = \deg f_i, \quad d_0 = \min_i d_i.$$
    Then $u^a x^b$ has bidegree $(|a|, \deg(f^a x^b) - |a| d_0)$, which is what
    its image $f^a x^b t^{|a|}$ records, so the relations are bihomogeneous
    whatever the degrees of the $f_i$. When the $f_i$ share a degree this is the
    grading $\deg u_i = (1,0)$ of the paper.

    Levelling the generators instead -- replacing $J$ by the ideal generated by
    its top-degree part -- is what this used to do, and it is unsound over a
    weighted base; see @TO singleDegreeIdeal@. {\tt UniformDegree} still forces
    that behaviour, but it is no longer the default.

    With {\tt BaseIsProjective => false} the base is taken to be
    $\operatorname{Spec} R$ instead.  The $x$ variables then carry no grading, the
    relations $u_i - f_i t$ are homogeneous in $u$ whatever the degrees of the
    $f_i$, and no replacement of $J$ is needed.
SeeAlso
  BaseIsProjective
///

doc ///
Key
  BaseIsProjective
Headline
  whether the base of a B2M projection is Proj R or Spec R
Description
  Text
    The paper works throughout with $X = \operatorname{Proj} R$ for a graded ring
    $R$, which is the default.  Passing {\tt BaseIsProjective => false} to
    @TO computeFlip@ or @TO bigradedReesProjection@ makes them work with
    $X = \operatorname{Spec} R$ for an arbitrary affine ring $R$.  The source $Z$
    then still sits in $\mathbf{P}^{r-1} \times X$, cut out by an ideal
    homogeneous in the fiber variables alone, so only the cone over the base
    disappears: the irrelevant ideal becomes $\langle u_1,\dots,u_r\rangle$ and
    one cone direction fewer is subtracted from Krull dimensions.

    An affine base is outside the scope of the paper.  It is provided because it
    makes computations at a single non-Q-Gorenstein singularity far cheaper than
    writing down a projective threefold containing it; see
    {\tt examples/toric-flip.m2}.  @TO b2mToGraphMorphism@ has no affine
    analogue and refuses to run on such a projection.
///

doc ///
Key
  singleDegreeIdeal
  (singleDegreeIdeal, Ideal, ZZ)
Headline
  the ideal generated by the degree-D part
Usage
  J' = singleDegreeIdeal(J, D)
Inputs
  J:Ideal
  D:ZZ
Outputs
  J':Ideal
Caveat
  This used to be how @TO bigradedReesProjection@ forced the generators of
  $I^{(m)}$ into a single degree, on the grounds that the result defines the
  same ideal sheaf once $D$ is at least the largest degree of a generator. That
  holds for the standard grading, where $R_a R_b = R_{a+b}$, but is {\em false}
  for weighted gradings, and it is no longer used by default.

  The ideal generated by $J_D$ is $\sum_i R_{D-d_i} f_i$, and in a weighted ring
  $R_{D-d_i}$ can vanish, dropping $f_i$ outright. Enlarging $D$ does not repair
  this: the $D$ that do preserve the sheaf are sparse and not monotone, and
  sometimes none exists. @TO bigradedReesIdeal@ weights the fibre variables
  instead.
///

doc ///
Key
  multiplierSchedule
  (multiplierSchedule, ZZ)
Headline
  the multipliers m tried by computeFlip
Usage
  ms = multiplierSchedule n
Inputs
  n:ZZ
Outputs
  ms:List
    every divisor of $n!$, in increasing order
Description
  Text
    The paper runs Step 4 over $m = 1!, 2!, 3!, \dots$. One $m$ that works is as
    good as another, so what matters is finding a small one: the cost of an
    iteration grows very steeply in $m$, because the number of generators of
    $I^{(m)}$ -- and with it the number of variables of the Rees algebra -- grows
    with $m$. On the threefold of {\tt examples/toric-flip.m2} one iteration
    costs 0.02 s at $m=1$, 0.9 s at $m=6$, 7 s at $m=8$, and more than ten
    minutes at $m=12$.

    Taking every divisor of $n!$ still contains $1!, \dots, n!$, so the
    termination guarantee is unchanged, and filling in the gaps is nearly free
    because the largest $m$ tried dominates the total: running all of
    $1,2,3,4,6,8$ costs 8.5 seconds against more than 600 for $m=12$ alone.
  Example
    multiplierSchedule 4
SeeAlso
  computeFlip
///

doc ///
Key
  canonicalIdeal
  (canonicalIdeal, Ring)
Headline
  the canonical module embedded in R as an ideal of least degree
Usage
  I = canonicalIdeal R
Inputs
  R:Ring
Outputs
  I:Ideal
    an ideal of $R$ isomorphic to $\omega_R$
Description
  Text
    Steps 2 and 3 of Algorithm 3 together amount to embedding $\omega_X$ into
    $R$ as an ideal: the ideal $I = \mathcal{O}_X(K_X - \operatorname{div}(s))$
    of Step 3 is isomorphic to $\omega_X$, and every ideal isomorphic to
    $\omega_X$ arises this way. Rather than choosing $s$ and then forming the
    ideal, this takes a nonzero homomorphism $\omega_X \to R$ of least degree,
    that is a minimal-degree generator of $\operatorname{Hom}(\omega_X, R)$, and
    returns its image.

    It matters which one is used. The $s$ that @TO antiCanonicalSection@
    produces depends on which representative of the canonical class the
    {\tt Divisor} package returns, and that depends on the grading. On the
    threefold of {\tt examples/toric-flip-projective.m2}, graded by
    $(2,2,1)$, that route gives $s = y_3^{11}$ and an $I^{(1)}$ in degree 30,
    which does not finish; the least-degree embedding gives generators of degree
    2 and takes a twentieth of a second.
SeeAlso
  antiCanonicalSection
  flipDivisorData
///

doc ///
Key
  isSmallProjection
  (isSmallProjection, B2MProjection)
Headline
  test whether the exceptional locus has codimension at least two
Usage
  isSmallProjection P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    Reports that $\pi$ is small exactly when no codimension-one component of
    $V(J\mathcal{O}_Z)$ is contracted, $J$ being the blown up ideal.

    That is equivalent to $\operatorname{codim}\operatorname{Exc}(\pi) \ge 2$.
    The exceptional locus is contained in $V(J\mathcal{O}_Z)$, since the blowup
    is an isomorphism wherever $J$ is invertible and $J$ is invertible outside
    $V(J)$. Now $J\mathcal{O}_Z$ is invertible by construction, so
    $V(J\mathcal{O}_Z)$ is an effective Cartier divisor and therefore pure of
    codimension one; a codimension-one component $D$ of the exceptional locus is
    thus a {\em component} of $V(J\mathcal{O}_Z)$ and not merely contained in
    one, because the component containing it has the same dimension. Finally,
    since $X$ is normal and $\pi$ is projective birational, Zariski's main
    theorem makes $\pi$ an isomorphism near any point with finite fibre, so
    components of the exceptional locus are exactly the contracted ones.
Caveat
  By the same argument every relevant component already has codimension one, so
  the dimension test in the implementation cannot fail; it is kept as a safety
  net, and what decides the answer is whether a component is contracted.
///

doc ///
Key
  isS2Source
  (isS2Source, B2MProjection)
Headline
  test Serre's condition S2 on the source
Usage
  isS2Source P
Inputs
  P:B2MProjection
Outputs
  :Boolean
Description
  Text
    For a {\em small} projection this is all that has to be checked in order to
    know that $Z$ is normal. A point $z$ of $Z$ of codimension one cannot lie in
    $\operatorname{Exc}(\pi)$, which has codimension at least two, so $\pi$ is a
    local isomorphism at $z$ and $\mathcal{O}_{Z,z}$ is the local ring of $X$ at
    a point of codimension one, hence a discrete valuation ring. A small
    projection therefore satisfies $R_1$ for free.

    The criterion {\tt isNormal} uses for its own $S_2$ half is that
    $\operatorname{codim}\operatorname{Ext}^j(A,S) \ge j+2$ for every
    $j > \operatorname{codim} I$; the locus where it fails is the union over $j$
    of the components of $\operatorname{Supp}\operatorname{Ext}^j$ of
    codimension at most $j+1$. Since $Z$ is covered by the primes of $A$ that do
    not contain the irrelevant ideal, $Z$ satisfies $S_2$ exactly when every
    such bad component lies in the irrelevant locus. That is the same step as in
    @TO isSmallProjection@, and it needs neither an affine cover nor a Veronese
    computation.

    Applying the criterion to the whole of $\operatorname{Spec} A$ instead --
    that is, asking the cone to be $S_2$ -- is strictly more than Lemma 7.2 asks
    for, because the vertex locus
    $V(A_+) \cong \operatorname{Spec} R$ has codimension one in
    $\operatorname{Spec} A$.
    The test is sufficient whatever the weights: writing $B = A_f$ for a
    relevant homogeneous $f$, $B$ is finite over $B' = B_0[f,f^{-1}]$ and $B'$
    is a direct summand of $B$ as a $B'$-module, so $B$ being $S_2$ forces
    $B_0 = A_{(f)}$ to be $S_2$. It is moreover {\em necessary}, hence exactly
    the condition of Lemma 7.2, when every relevant variable has weight one: the
    torus then acts freely on $\operatorname{Spec} A \setminus V(\mathrm{irr})$,
    which becomes a torsor over $Z$ and lets $S_2$ travel in both directions.
    That covers an affine base and a projective base with the standard grading.
Caveat
  On its own this does not say that $Z$ is normal: it has to be combined with
  @TO isSmallProjection@.

  Over a weighted grading only sufficiency is claimed. That costs nothing in
  correctness: a sufficiently factorial $m$ makes
  $A = \bigoplus_k \mathcal{O}_X(-kmE)$, a divisorial algebra over a normal ring
  and hence normal, so the test is certain to fire by then. At worst
  @TO computeFlip@ tries one more $m$ than strictly necessary.
SeeAlso
  isNormalSource
  isSmallProjection
///

doc ///
Key
  b2mToGraphMorphism
  (b2mToGraphMorphism, B2MProjection)
Headline
  transform a B2M projection into a graph morphism
Usage
  G = b2mToGraphMorphism P
Inputs
  P:B2MProjection
Outputs
  G:GraphMorphism
Description
  Text
    This is Lemma 2.6 of arXiv:2603.13703.  The source of the projection is
    turned into a monograded variety by means of the Segre isomorphism of
    Section 2.2, and the graph of the resulting morphism is computed as a
    bigraded variety.
///
