-- Step 5 of Algorithm 3: the Rees algebra R[I^(m) t] as a bigraded ring, the
-- resulting B2M projection Z^m = Proj R[I^(m)t] --> X = Proj R, and the two tests
-- of Lemma 7.2 (normality of Z^m and codimension of the exceptional locus).

-- The paper puts deg(u_i) = (0,1) and deg(f) = (s,0) for f in R of degree s.
-- For the defining relations of the Rees algebra to be bihomogeneous in that
-- grading, the generators f_1, ..., f_r of the ideal must all have the same
-- degree D: the relations then have u-degree n and x-degree e with e - nD
-- constant.  We therefore replace I^(m) by the ideal generated by its degree-D
-- part, which defines the same ideal sheaf as soon as D is at least the largest
-- degree of a generator.
--
-- Over an affine base none of this is needed: the x variables carry no grading,
-- so u_i - t f_i is homogeneous of u-degree 1 whatever the f_i are.
singleDegreeIdeal = method()
singleDegreeIdeal (Ideal, ZZ) := (J, D) -> (
    R := ring J;
    gs := first entries gens image basis(D, module J);
    if #gs == 0 then error("singleDegreeIdeal: no elements of degree " | toString D);
    ideal gs
    )

-- The smallest degree in which we may take generators.
uniformDegree = method()
uniformDegree Ideal := J -> max apply(flatten degrees J, identity)

-- Rees algebra of an ideal of R, presented as an ideal of k[u_1..u_r, x_1..x_n].
--
-- Projective base: the generators f_i must share a single degree D, and the
-- presentation is bigraded with deg(u_i) = (1,0) and deg(x_j) = (0,c_j).
-- Affine base: the presentation is graded by the u-degree alone, which we leave
-- implicit and compute with the standard grading.
--
-- Either way the ideal is the kernel of
--     k[u,x] --> R[t],  u_i |--> f_i t,
-- computed by eliminating t.  In the graded case t is given the degree (1,-D)
-- so that the elimination stays homogeneous.
bigradedReesIdeal = method(Options => {BaseIsProjective => true})
bigradedReesIdeal Ideal := o -> J -> (
    R := ring J;
    A := ambient R;
    IX := ideal R;
    fs := first entries gens J;
    if #fs == 0 then error "bigradedReesIdeal: zero ideal";
    r := #fs;
    n := numgens A;
    kk := coefficientRing A;
    uu := getSymbol "u";
    tt := getSymbol "t";
    (T, Abig) := if o.BaseIsProjective then (
        ds := apply(fs, f -> (degree f)#0);
        if #(set ds) != 1 then error "bigradedReesIdeal: generators are not of a single degree";
        D := first ds;
        xdegs := apply(degrees A, d -> {0, d#0});
        (kk(monoid [tt, uu_1 .. uu_r, gens A,
                Degrees => {{1, -D}} | toList(r : {1,0}) | xdegs,
                Heft => {D+1, 1},
                MonomialOrder => Eliminate 1]),
         kk(monoid [uu_1 .. uu_r, gens A,
                Degrees => toList(r : {1,0}) | xdegs,
                Heft => {1, 1}]))
        ) else (
        (kk(monoid [tt, uu_1 .. uu_r, gens A, MonomialOrder => Eliminate 1]),
         kk(monoid [uu_1 .. uu_r, gens A]))
        );
    xT := take(gens T, {r+1, r+n});
    phi := map(T, A, xT);
    L := phi IX + ideal apply(r, i ->
        (gens T)#(i+1) - (gens T)#0 * phi lift(fs#i, A));
    G := selectInSubring(1, gens gb L);
    psi := map(Abig, T, {0_Abig} | gens Abig);
    (Abig, ideal psi G)
    )

-- The B2M projection Z = Proj R[Jt] --> X (Definition 2.4).
bigradedReesProjection = method(Options => {UniformDegree => null, BaseIsProjective => true})
bigradedReesProjection Ideal := o -> J -> (
    R := ring J;
    D := if not o.BaseIsProjective then null
        else if o.UniformDegree === null then uniformDegree J else o.UniformDegree;
    J' := if o.BaseIsProjective then singleDegreeIdeal(J, D) else trim J;
    (Abig, IZ) := bigradedReesIdeal(J', BaseIsProjective => o.BaseIsProjective);
    r := numgens J';
    n := numgens ambient R;
    us := take(gens Abig, r);
    xs := take(gens Abig, {r, r+n-1});
    incl := map(Abig, ambient R, xs);
    b2mProjection new HashTable from {
        ambientRing => Abig,
        definingIdeal => IZ,
        totalRing => Abig/IZ,
        baseRing => R,
        fiberVariables => us,
        baseVariables => xs,
        baseIsProjective => o.BaseIsProjective,
        irrelevantIdeal => (if o.BaseIsProjective
            then bigradedIrrelevantIdeal(us, xs) else affineIrrelevantIdeal us),
        blownUpIdeal => ideal incl lift(gens J', ambient R),
        uniformDegreeUsed => D
        }
    )

b2mProjection = method()
b2mProjection HashTable := H -> new B2MProjection from H

-- Normality of Z (the first condition of Lemma 7.2).
--
-- We test normality of the bihomogeneous coordinate ring, i.e. of the affine
-- cone over Z, which is a sufficient but not necessary condition for Z itself to
-- be normal.
isNormalSource = method()
isNormalSource B2MProjection := P -> isNormal(P#totalRing)

-- Codimension of the exceptional locus (the second condition of Lemma 7.2).
--
-- Write J for the blown up ideal.  Over the open locus where J is invertible the
-- projection pi is an isomorphism, so Exc(pi) is contained in V(J O_Z).  Since X
-- is normal and pi is projective and birational, Zariski's main theorem shows
-- that pi is an isomorphism near any point where it is finite; hence a
-- codimension-one component of Exc(pi) has to be a codimension-one irreducible
-- component of V(J O_Z) that is contracted by pi.  We therefore look for such
-- components.
isSmallProjection = method(Options => {Verbose => false})
isSmallProjection B2MProjection := o -> P -> (
    dZ := geometricDimension P;
    JU := trim (P#definingIdeal + P#blownUpIdeal);
    comps := select(minimalPrimes JU, q -> definesNonemptyLocus(q, P#irrelevantIdeal));
    bad := select(comps, q -> (
        dq := bigradedDim(P, q);
        contracted := imageDimension(P, q) < dq;
        if o.Verbose then << "  component of dim " << dq
            << (if contracted then " (contracted)" else " (not contracted)") << endl;
        contracted and dq > dZ - 2));
    #bad == 0
    )
