-- Step 5 of Algorithm 3: the Rees algebra R[I^(m) t] as a bigraded ring, the
-- resulting B2M projection Z^m = Proj R[I^(m)t] --> X = Proj R, and the two tests
-- of Lemma 7.2 (normality of Z^m and codimension of the exceptional locus).

-- The paper puts deg(u_i) = (0,1) and deg(f) = (s,0) for f in R of degree s.
-- For the defining relations of the Rees algebra to be bihomogeneous in that
-- grading, the generators f_1, ..., f_r of the ideal must all have the same
-- degree D: the relations then have u-degree n and x-degree e with e - nD
-- constant.  We therefore replace I^(m) by the ideal generated by its degree-D
-- part, which defines the same ideal sheaf as soon as D is at least the largest
-- degree of a generator.
--
-- Over an affine base none of this is needed: the x variables carry no grading,
-- so u_i - t f_i is homogeneous of u-degree 1 whatever the f_i are.
singleDegreeIdeal = method()
singleDegreeIdeal (Ideal, ZZ) := (J, D) -> (
    R := ring J;
    gs := first entries gens image basis(D, module J);
    if #gs == 0 then error("singleDegreeIdeal: no elements of degree " | toString D);
    ideal gs
    )

-- The smallest degree in which we may take generators.
uniformDegree = method()
uniformDegree Ideal := J -> max apply(flatten degrees J, identity)

-- Rees algebra of an ideal of R, presented as an ideal of k[u_1..u_r, x_1..x_n].
--
-- Projective base: the generators f_i must share a single degree D, and the
-- presentation is bigraded with deg(u_i) = (1,0) and deg(x_j) = (0,c_j).
-- Affine base: the presentation is graded by the u-degree alone, which we leave
-- implicit and compute with the standard grading.
--
-- Either way the ideal is the kernel of
--     k[u,x] --> R[t],  u_i |--> f_i t,
-- computed by eliminating t.  In the graded case t is given the degree (1,-D)
-- so that the elimination stays homogeneous.
bigradedReesIdeal = method(Options => {BaseIsProjective => true})
bigradedReesIdeal Ideal := o -> J -> (
    R := ring J;
    A := ambient R;
    IX := ideal R;
    fs := first entries gens J;
    if #fs == 0 then error "bigradedReesIdeal: zero ideal";
    r := #fs;
    n := numgens A;
    kk := coefficientRing A;
    uu := getSymbol "u";
    tt := getSymbol "t";
    (T, Abig) := if o.BaseIsProjective then (
        ds := apply(fs, f -> (degree f)#0);
        if #(set ds) != 1 then error "bigradedReesIdeal: generators are not of a single degree";
        D := first ds;
        xdegs := apply(degrees A, d -> {0, d#0});
        (kk(monoid [tt, uu_1 .. uu_r, gens A,
                Degrees => {{1, -D}} | toList(r : {1,0}) | xdegs,
                Heft => {D+1, 1},
                MonomialOrder => Eliminate 1]),
         kk(monoid [uu_1 .. uu_r, gens A,
                Degrees => toList(r : {1,0}) | xdegs,
                Heft => {1, 1}]))
        ) else (
        (kk(monoid [tt, uu_1 .. uu_r, gens A, MonomialOrder => Eliminate 1]),
         kk(monoid [uu_1 .. uu_r, gens A]))
        );
    xT := take(gens T, {r+1, r+n});
    phi := map(T, A, xT);
    L := phi IX + ideal apply(r, i ->
        (gens T)#(i+1) - (gens T)#0 * phi lift(fs#i, A));
    G := selectInSubring(1, gens gb L);
    psi := map(Abig, T, {0_Abig} | gens Abig);
    (Abig, ideal psi G)
    )

-- The B2M projection Z = Proj R[Jt] --> X (Definition 2.4).
bigradedReesProjection = method(Options => {UniformDegree => null, BaseIsProjective => true})
bigradedReesProjection Ideal := o -> J -> (
    R := ring J;
    D := if not o.BaseIsProjective then null
        else if o.UniformDegree === null then uniformDegree J else o.UniformDegree;
    J' := if o.BaseIsProjective then singleDegreeIdeal(J, D) else trim J;
    (Abig, IZ) := bigradedReesIdeal(J', BaseIsProjective => o.BaseIsProjective);
    r := numgens J';
    n := numgens ambient R;
    us := take(gens Abig, r);
    xs := take(gens Abig, {r, r+n-1});
    incl := map(Abig, ambient R, xs);
    b2mProjection new HashTable from {
        ambientRing => Abig,
        definingIdeal => IZ,
        totalRing => Abig/IZ,
        baseRing => R,
        fiberVariables => us,
        baseVariables => xs,
        baseIsProjective => o.BaseIsProjective,
        irrelevantIdeal => (if o.BaseIsProjective
            then bigradedIrrelevantIdeal(us, xs) else affineIrrelevantIdeal us),
        blownUpIdeal => ideal incl lift(gens J', ambient R),
        uniformDegreeUsed => D
        }
    )

b2mProjection = method()
b2mProjection HashTable := H -> new B2MProjection from H

-- Normality of Z (the first condition of Lemma 7.2), in two versions.
--
-- The full test asks the bihomogeneous coordinate ring, i.e. the affine cone
-- over Z, to be normal.  That is sufficient but not necessary for Z itself to be
-- normal, and it is expensive: isNormal checks S2 and then R1, and the R1 half
-- goes through minors(codim I, jacobian), which explodes.
isNormalSource = method()
isNormalSource B2MProjection := P -> isNormal(P#totalRing)

-- Serre's condition S2 for Z.
--
-- Once the projection is known to be small this is all that has to be checked.
-- A point z of Z of codimension one does not lie in Exc(pi), because that has
-- codimension at least two, so pi is a local isomorphism at z and O_{Z,z} is the
-- local ring of X at a point of codimension one, hence a discrete valuation ring.
-- A small projection therefore has R1 for free, and normality reduces to S2.
--
-- The criterion isNormal uses for its own S2 half is: A = S/I is S2 when
-- codim Ext^j(A,S) >= j+2 for every j > codim I.  The locus where it fails is
-- the union over j of the components of Supp Ext^j of codimension at most j+1.
-- Z is covered by the primes of A that do not contain the irrelevant ideal, so
-- Z is S2 exactly when every such bad component lies in the irrelevant locus --
-- the same "discard the components that define the empty set" step as in
-- isSmallProjection, and it needs neither charts nor a Veronese computation.
--
-- Applying the criterion on the whole of Spec A instead would also cover the
-- primes containing the irrelevant ideal, which is strictly more than Lemma 7.2
-- asks for: the vertex locus V(A_+) is isomorphic to Spec R and has codimension
-- one in Spec A, so requiring S2 there can reject an m that in fact works.
--
-- The test is always sufficient, whatever the weights.  Writing B = A_f for a
-- relevant homogeneous f, B is finite over B' = B_0[f,f^{-1}] and B' is a direct
-- summand of B as a B'-module, so depth B' >= depth B while the dimensions
-- agree; hence B S2 gives B_0 = A_(f) S2, which is S2 for the chart of Z.
--
-- It is moreover necessary, so exactly Lemma 7.2's condition, when every
-- relevant variable has weight one: the torus then acts freely on
-- Spec A - V(irr), which becomes a torsor over Z and lets S2 travel both ways.
-- That covers an affine base and a projective base with the standard grading.
-- Over weighted gradings only sufficiency is claimed, which costs nothing in
-- correctness: the algorithm may try one more m than strictly necessary, but a
-- sufficiently factorial m makes A = (+)_k O_X(-kmE), a divisorial algebra over
-- a normal ring and hence normal, so the test is certain to fire by then.
isS2Source = method()
isS2Source B2MProjection := P -> (
    A := P#ambientRing;
    I := P#definingIdeal;
    irr := P#irrelevantIdeal;
    n := codim I;
    M := cokernel generators I;
    all(toList(n+1 .. (dim A) - 1), j -> (
        E := Ext^j(M, A);
        E == 0 or all(minimalPrimes ann E,
            q -> codim q >= j+2 or isSubset(irr, q))))
    )

-- Codimension of the exceptional locus (the second condition of Lemma 7.2).
--
-- Write J for the blown up ideal.  Over the open locus where J is invertible the
-- projection pi is an isomorphism, so Exc(pi) is contained in V(J O_Z).  Since X
-- is normal and pi is projective and birational, Zariski's main theorem shows
-- that pi is an isomorphism near any point where it is finite; hence a
-- codimension-one component of Exc(pi) has to be a codimension-one irreducible
-- component of V(J O_Z) that is contracted by pi.  We therefore look for such
-- components.
isSmallProjection = method(Options => {Verbose => false})
isSmallProjection B2MProjection := o -> P -> (
    dZ := geometricDimension P;
    JU := trim (P#definingIdeal + P#blownUpIdeal);
    comps := select(minimalPrimes JU, q -> definesNonemptyLocus(q, P#irrelevantIdeal));
    bad := select(comps, q -> (
        dq := bigradedDim(P, q);
        contracted := imageDimension(P, q) < dq;
        if o.Verbose then << "  component of dim " << dq
            << (if contracted then " (contracted)" else " (not contracted)") << endl;
        contracted and dq > dZ - 2));
    #bad == 0
    )
